name: Release OpenPrompt

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            output_name: openprompt-linux
            asset_name: openprompt-linux-amd64
          - os: windows-latest
            output_name: openprompt-windows.exe
            asset_name: openprompt-windows-amd64.exe
          - os: macos-latest
            output_name: openprompt-macos
            asset_name: openprompt-macos-amd64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go mod download

      - name: Build
        run: |
          go build -v -o ${{ matrix.output_name }} ./cmd

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.output_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
